backend:
  name: github
  repo: "StarAtty/staratty.github.io"

site_url: "staratt.ml"
media_folder: "static/img"
public_folder: "/img"

collections:
  - name: 'posts'
    label: '文章'
    description: >
      寫點東西吧～
    folder: 'content/posts'
    create: true
    slug: '{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields:
      - { label: '標題', name: 'title', widget: 'string' }
      - { label: '發布日期', name: 'date', widget: 'datetime' }
      - { label: '摘要', name: 'description', widget: 'string' }
      - { label: '內容', name: 'body', widget: 'markdown' }
      - { label: "標籤", name: "tags", widget: "list", required: false}
